name: Build and Test

on:
  push:
    branches:
      # - master   # push on master is not possible anymore
      - feature/*
  pull_request:
    branches:
      - master
      - v1
      - test

jobs:
  lint-and-test:
    strategy:
      matrix:
        go-version: [1.18.1, 1.19.13, 1.20.14, 1.21.10, 1.22.3]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
      - name: Run tests
        run: go test -failfast -v -race -timeout=1m -covermode=atomic

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.3
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Calc coverage
        run: |
          go test -v -covermode=count -coverprofile=coverage.out
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
